backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads

collections:
  - name: "location" # Used in routes, e.g., /admin/collections/blog
    label: "Location" # Used in the UI
    folder: "_posts/locations" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter
      - {label: "Ort", name: "ort", widget: "string"}
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Collection ID", name: "collectionId", widget: "string"}
      - {label: "Item ID", name: "itemId", widget: "string"}
      - {label: "Created On", name: "createdOn", widget: "datetime"}
      - {label: "Updated On", name: "updatedOn", widget: "datetime"}
      - {label: "Published On", name: "publishedOn", widget: "datetime"}
